// <auto-generated />
namespace Malteser.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users));
        
        string IMigrationMetadata.Id
        {
            get { return "201407071516036_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
